#!/usr/bin/env python
# coding: utf-8

# In[41]:


import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import scipy


# In[42]:


def imread(path, is_grayscale=True):
  """
  Read image using its path.
  
  Default value is gray-scale, and image is read by YCbCr format as the paper said.
  """
  #path= "E\image"
  
  if is_grayscale:
    return scipy.misc.imread(path, flatten=True, mode='YCbCr').astype(np.float)
  else:
    return scipy.misc.imread(path, mode='YCbCr').astype(np.float)


# In[43]:


def modcrop(image, scale=3):
  """
  To scale down and up the original image, first thing to do is to have no remainder while scaling operation.
  
  We need to find modulo of height (and width) and scale factor.
  Then, subtract the modulo from height (and width) of original image size.
  There would be no remainder even after scaling operation.
  """
  if len(image.shape) == 3:
    h, w, _ = image.shape
    h = h - np.mod(h, scale)
    w = w - np.mod(w, scale)
    image = image[0:h, 0:w, :]
    else:
    h, w = image.shape
    h = h - np.mod(h, scale)
    w = w - np.mod(w, scale)
    image = image[0:h, 0:w]
    return image


# In[44]:


def preprocess(path, scale=3):
  """
  Preprocess single image file 
    (1) Read original image as YCbCr format (and grayscale as default)
    (2) Normalize
    (3) Apply image file with bicubic interpolation
  Args:
    path: file path of desired file
    input_: image applied bicubic interpolation (low-resolution)
    label_: image with original resolution (high-resolution)
  """
    image = imread(path, is_grayscale=True)
    label_ = modcrop(image, scale)

  # Must be normalized
    image = image / 255.
    label_ = label_ / 255.

    input_ = scipy.ndimage.interpolation.zoom(label_, (1./scale), prefilter=False)
    input_ = scipy.ndimage.interpolation.zoom(input_, (scale/1.), prefilter=False)

    return input_, label_


# In[45]:


c_dim = 1
input_size = 255

"""Define the model weights and biases 
"""

# define the placeholders for inputs and outputs
inputs = tf.placeholder(tf.float32, [None, input_size, input_size, c_dim], name='inputs')
ouputs = tf.placeholder(tf.float32, [None, input_size, input_size, c_dim], name='outputs')
## ------ Add your code here: set the weight of three conv layers
# replace '0' with your hyper parameter numbers 
# conv1 layer with biases: 64 filters with size 9 x 9
# conv2 layer with biases and relu: 32 filters with size 1 x 1
# conv3 layer with biases and NO relu: 1 filter with size 5 x 5
weights = {
    'w1': tf.Variable(tf.random_normal([9, 9, 1, 64], stddev=1e-3), name='w1'),
    'w2': tf.Variable(tf.random_normal([1, 1, 64, 32], stddev=1e-3), name='w2'),
    'w3': tf.Variable(tf.random_normal([5, 5, 32, 1], stddev=1e-3), name='w3')
    }

biases = {
      'b1': tf.Variable(tf.zeros([64]), name='b1'),
      'b2': tf.Variable(tf.zeros([32]), name='b2'),
      'b3': tf.Variable(tf.zeros([1]), name='b3')
    }

"""Define the model layers with three convolutional layers
"""
## ------ Add your code here: to compute feature maps of input low-resolution images
# replace 'None' with your layers: use the tf.nn.conv2d() and tf.nn.relu()
# conv1 layer with biases and relu : 64 filters with size 9 x 9
conv1 = tf.nn.relu(tf.nn.conv2d(inputs, weights['w1'], strides=[1,1,1,1], padding='VALID') + biases['b1'])
#conv1 = tf.layers.conv2d(inputs,filters=64,kernel_size=[9, 9],padding="VALID",activation=tf.nn.relu)

##------ Add your code here: to compute non-linear mapping
# conv2 layer with biases and relu: 32 filters with size 1 x 1
conv2 = tf.nn.relu(tf.nn.conv2d(conv1, weights['w2'], strides=[1,1,1,1], padding='VALID') + biases['b2'])
#conv2 = tf.layers.conv2d(conv1,filters=32,kernel_size=[1,1],padding="VALID",activation=tf.nn.relu)

##------ Add your code here: compute the reconstruction of high-resolution image
# conv3 layer with biases and NO relu: 1 filter with size 5 x 5
conv3 = tf.nn.conv2d(conv2, weights['w3'], strides=[1,1,1,1], padding='VALID') + biases['b3']
#conv3 = tf.layers.conv2d(conv2,filters=1,kernel_size=[5,5],padding="VALID")



# In[46]:


#Load the pre-trained model file
model_path="./model.npy"
model = np.load(model_path, encoding='latin1').item()


# In[47]:


#show the weights of model
w1weight = model['w1']
w2weight = model['w2']
w3weight = model['w3']


# In[48]:


#Visualizing with variable w1weight
fig = plt.figure(figsize=(8, 8))
for i in range(64):
    sub = fig.add_subplot(8, 8, i + 1)
    sub.imshow(w1weight[:, :, 0, i], cmap='gray')
    plt.axis('off')
plt.show()


# In[49]:


#Visualizing with variable w2weight
fig=plt.figure(figsize=(8, 8))
for i in range(32):
    sub = fig.add_subplot(4, 8, i + 1)
    sub.imshow(w2weight[:, :, 0, i], cmap='gray')
    plt.axis('off')
plt.show()


# In[50]:


#Visualizing with variable w3weight
plt.figure(figsize=(8, 8))
plt.imshow(w3weight[:, :, 0, 0], cmap='gray')
plt.axis('off')
plt.show()


# In[51]:


# launch a session
sess = tf.Session()

for key in weights.keys():
    sess.run(weights[key].assign(model[key]))

for key in biases.keys():
    sess.run(biases[key].assign(model[key]))


# In[52]:


#Read the test image
blurred_image, groudtruth_image = preprocess("./butterfly_GT.bmp")


# In[53]:


type(groudtruth_image)


# In[54]:


groudtruth_image.shape


# In[55]:


type(blurred_image)


# In[56]:


blurred_image.shape


# In[57]:


# transform the input to 4-D tensor
input_ = np.expand_dims(np.expand_dims(blurred_image, axis =0), axis=-1)


# In[58]:


output1=sess.run(conv1,feed_dict={inputs:input_})
output2=sess.run(conv2,feed_dict={inputs:input_})
output3=sess.run(conv3,feed_dict={inputs:input_})


# In[59]:


output3.shape


# In[60]:


scipy.misc.imsave("blurred_image.jpg",blurred_image)


# In[61]:


plt.imshow(blurred_image)
#plt.imshow(blurred_image,cmap="gray")
plt.axis("off")


# In[62]:


blurred_image.shape


# In[63]:


scipy.misc.imsave("groudtruth_image.jpg",groudtruth_image)


# In[64]:


plt.imshow(groudtruth_image)
#plt.imshow(groudtruth_image,cmap="gray")
plt.axis("off")


# In[65]:


groudtruth_image.shape


# In[66]:


groudtruth_image[6:249,6:249].shape


# In[67]:


HR_image=output3[0,:,:,0]
plt.imshow(HR_image)
#plt.imshow(HR_image,cmap="gray")
plt.axis("off")


# In[68]:


HR_image.shape


# In[69]:


import skimage
Super_resolution_output=skimage.measure.compare_psnr(HR_image,groudtruth_image[6:249,6:249])
print("Super resolution PSNR : ",Super_resolution_output)


# In[70]:


output_bicubic=skimage.measure.compare_psnr(blurred_image,groudtruth_image)
print("Bicubic PSNR : ",output_bicubic)





